# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sequence.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sequence.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0esequence.proto\x12\x08protobuf\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n\x0fIncrementNumber\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x03\",\n\x0f\x46ibonacciNumber\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03\")\n\x0cUniqueString\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t2\xb6\x02\n\x08Sequence\x12\x65\n\tIncrement\x12\x16.google.protobuf.Empty\x1a\x19.protobuf.IncrementNumber\"%\x82\xd3\xe4\x93\x02\x1f\"\x1a/api/v1/sequence/increment:\x01*\x12\x65\n\tFibonacci\x12\x16.google.protobuf.Empty\x1a\x19.protobuf.FibonacciNumber\"%\x82\xd3\xe4\x93\x02\x1f\"\x1a/api/v1/sequence/fibonacci:\x01*\x12\\\n\x06Unique\x12\x16.google.protobuf.Empty\x1a\x16.protobuf.UniqueString\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/api/v1/sequence/unique:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_INCREMENTNUMBER = _descriptor.Descriptor(
  name='IncrementNumber',
  full_name='protobuf.IncrementNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.IncrementNumber.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.IncrementNumber.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=131,
)


_FIBONACCINUMBER = _descriptor.Descriptor(
  name='FibonacciNumber',
  full_name='protobuf.FibonacciNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.FibonacciNumber.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.FibonacciNumber.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=177,
)


_UNIQUESTRING = _descriptor.Descriptor(
  name='UniqueString',
  full_name='protobuf.UniqueString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.UniqueString.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.UniqueString.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['IncrementNumber'] = _INCREMENTNUMBER
DESCRIPTOR.message_types_by_name['FibonacciNumber'] = _FIBONACCINUMBER
DESCRIPTOR.message_types_by_name['UniqueString'] = _UNIQUESTRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IncrementNumber = _reflection.GeneratedProtocolMessageType('IncrementNumber', (_message.Message,), dict(
  DESCRIPTOR = _INCREMENTNUMBER,
  __module__ = 'sequence_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.IncrementNumber)
  ))
_sym_db.RegisterMessage(IncrementNumber)

FibonacciNumber = _reflection.GeneratedProtocolMessageType('FibonacciNumber', (_message.Message,), dict(
  DESCRIPTOR = _FIBONACCINUMBER,
  __module__ = 'sequence_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.FibonacciNumber)
  ))
_sym_db.RegisterMessage(FibonacciNumber)

UniqueString = _reflection.GeneratedProtocolMessageType('UniqueString', (_message.Message,), dict(
  DESCRIPTOR = _UNIQUESTRING,
  __module__ = 'sequence_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.UniqueString)
  ))
_sym_db.RegisterMessage(UniqueString)



_SEQUENCE = _descriptor.ServiceDescriptor(
  name='Sequence',
  full_name='protobuf.Sequence',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=223,
  serialized_end=533,
  methods=[
  _descriptor.MethodDescriptor(
    name='Increment',
    full_name='protobuf.Sequence.Increment',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_INCREMENTNUMBER,
    serialized_options=_b('\202\323\344\223\002\037\"\032/api/v1/sequence/increment:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='Fibonacci',
    full_name='protobuf.Sequence.Fibonacci',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_FIBONACCINUMBER,
    serialized_options=_b('\202\323\344\223\002\037\"\032/api/v1/sequence/fibonacci:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='Unique',
    full_name='protobuf.Sequence.Unique',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_UNIQUESTRING,
    serialized_options=_b('\202\323\344\223\002\034\"\027/api/v1/sequence/unique:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_SEQUENCE)

DESCRIPTOR.services_by_name['Sequence'] = _SEQUENCE

# @@protoc_insertion_point(module_scope)
